name: base
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
    - ipykernel
    - spacy<3.8
    - pytest 
    - PyRuSH
    - medspacy_quickumls
    - pysbd
    - jsonschema
    - jupyterlab