name: manual_test_pip

on:
  workflow_dispatch:
    inputs:
      install_prerelease:
        description: 'Check this to install the prerelease version of medspacy if available and the version is newer than formal release.'  
        type: boolean   
        required: false
        default: false
      python_38:
        description: 'Test with Python 3.8'
        type: boolean
        default: false
        required: false
      python_39:
        description: 'Test with Python 3.9'
        type: boolean
        default: false
        required: false
      python_310:
        description: 'Test with Python 3.10'
        type: boolean
        default: true
        required: false
      python_311:
        description: 'Test with Python 3.11'
        type: boolean
        default: false
        required: false
      python_312:
        description: 'Test with Python 3.12'
        type: boolean
        default: false
        required: false
      python_313:
        description: 'Test with Python 3.13'
        type: boolean
        default: false
        required: false



jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.get-python-versions.outputs.versions }}
    steps:
      - id: get-python-versions
        run: |
          VERSIONS=""
          if [[ "${{ github.event.inputs.python_38 }}" == "true" ]]; then
            VERSIONS='"3.8"'
          fi
          if [[ "${{ github.event.inputs.python_39 }}" == "true" ]]; then
            if [[ -n "$VERSIONS" ]]; then VERSIONS="$VERSIONS,"; fi
            VERSIONS="${VERSIONS}\"3.9\""
          fi
          if [[ "${{ github.event.inputs.python_310 }}" == "true" ]]; then
            if [[ -n "$VERSIONS" ]]; then VERSIONS="$VERSIONS,"; fi
            VERSIONS="${VERSIONS}\"3.10.x\""
          fi
          if [[ "${{ github.event.inputs.python_311 }}" == "true" ]]; then
            if [[ -n "$VERSIONS" ]]; then VERSIONS="$VERSIONS,"; fi
            VERSIONS="${VERSIONS}\"3.11.x\""
          fi
          if [[ "${{ github.event.inputs.python_312 }}" == "true" ]]; then
            if [[ -n "$VERSIONS" ]]; then VERSIONS="$VERSIONS,"; fi
            VERSIONS="${VERSIONS}\"3.12.x\""
          fi
          if [[ "${{ github.event.inputs.python_313 }}" == "true" ]]; then
            if [[ -n "$VERSIONS" ]]; then VERSIONS="$VERSIONS,"; fi
            VERSIONS="${VERSIONS}\"3.13.x\""
          fi
          # Default to 3.10.x if nothing is selected
          if [[ -z "$VERSIONS" ]]; then
            VERSIONS='"3.10.x"'
          fi
          echo "versions=[$VERSIONS]"
          echo "versions=[$VERSIONS]" >> $GITHUB_OUTPUT
        shell: bash

  test:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.8]
        python-version: ${{ needs.setup.outputs.versions || ["3.10.x"] }}

        # revised from https://github.com/actions/cache/blob/main/examples.md#python---pip
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Git clone repo and remove source code
      run: |
        pwd
        ls
        # remove cloned source code to ensure test on installed medspacy
        python -c "import shutil;shutil.rmtree('medspacy')"
        ls

    - name: Set up pip
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}   
        cache: 'pip'   
        cache-dependency-path: |
          'requirements/requirements.txt'
          'requirements/requirements_tests.txt'
    - run: |
        python --version
        pip install --upgrade pip
    
    
    - name: Install prereleased medspacy
      if: ${{ github.event.inputs.install_prerelease == 'true' }} 
      run: |
        # use this to avoid install prereleases of dependencies packages
        python -m pip install --use-pep517 -r requirements/requirements_tests.txt       
        pip install --pre medspacy

    - name: Install formal released medspacy
      if: ${{ github.event.inputs.install_prerelease == 'false' }}  
      run: |
        pip install medspacy

    - name: Install dependencies to run pytest
      run: |
        pip install --use-pep517 -r requirements/requirements_tests.txt
        python -m spacy download de_core_news_sm
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_md
        # multilingual models for testing compatibility
        python -m spacy download es_core_news_sm
        python -m spacy download pl_core_news_sm
        python -m spacy download de_core_news_sm
        python -m spacy download xx_ent_wiki_sm

    - name: print medspacy version
      run: python -c 'import medspacy; print(medspacy.__version__); print(medspacy.__file__)'
    
    - name: Test with pytest
      # need to run pytest after a clean pip install to 100% replicate the users' environment
      run: |        
        # run everything besides the QuickUMLS span group tests...
        pytest -k "not test_span_groups and not test_overlapping_spans and not test_multiword_span"
        # now in a separate session we can run the QuickUMLS span group tests...
        pytest -k "test_span_groups or test_overlapping_spans or test_multiword_span"
